// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.http.HttpHeaderName;
import com.azure.core.http.HttpHeaders;

/**
 * The AccessPolicyAssignmentsDeleteHeaders model.
 */
@Fluent
public final class AccessPolicyAssignmentsDeleteHeaders {
    /*
     * The Location property.
     */
    private String location;

    // HttpHeaders containing the raw property values.
    /**
     * Creates an instance of AccessPolicyAssignmentsDeleteHeaders class.
     * 
     * @param rawHeaders The raw HttpHeaders that will be used to create the property values.
     */
    public AccessPolicyAssignmentsDeleteHeaders(HttpHeaders rawHeaders) {
        this.location = rawHeaders.getValue(HttpHeaderName.LOCATION);
    }

    /**
     * Get the location property: The Location property.
     * 
     * @return the location value.
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * Set the location property: The Location property.
     * 
     * @param location the location value to set.
     * @return the AccessPolicyAssignmentsDeleteHeaders object itself.
     */
    public AccessPolicyAssignmentsDeleteHeaders setLocation(String location) {
        this.location = location;
        return this;
    }
}
