// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Built-In or Custom access policy.
 */
public final class AccessPolicyType extends ExpandableStringEnum<AccessPolicyType> {
    /**
     * Static value Custom for AccessPolicyType.
     */
    public static final AccessPolicyType CUSTOM = fromString("Custom");

    /**
     * Static value BuiltIn for AccessPolicyType.
     */
    public static final AccessPolicyType BUILT_IN = fromString("BuiltIn");

    /**
     * Creates a new instance of AccessPolicyType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public AccessPolicyType() {
    }

    /**
     * Creates or finds a AccessPolicyType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding AccessPolicyType.
     */
    public static AccessPolicyType fromString(String name) {
        return fromString(name, AccessPolicyType.class);
    }

    /**
     * Gets known AccessPolicyType values.
     * 
     * @return known AccessPolicyType values.
     */
    public static Collection<AccessPolicyType> values() {
        return values(AccessPolicyType.class);
    }
}
