// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Parameters for Redis import operation.
 */
@Fluent
public final class ImportRDBParameters implements JsonSerializable<ImportRDBParameters> {
    /*
     * File format.
     */
    private String format;

    /*
     * files to import.
     */
    private List<String> files;

    /*
     * Preferred auth method to communicate to storage account used for data archive, specify SAS or ManagedIdentity,
     * default value is SAS
     */
    private String preferredDataArchiveAuthMethod;

    /*
     * Subscription id of the storage container containing files to import using Managed Identity.
     */
    private String storageSubscriptionId;

    /**
     * Creates an instance of ImportRDBParameters class.
     */
    public ImportRDBParameters() {
    }

    /**
     * Get the format property: File format.
     * 
     * @return the format value.
     */
    public String getFormat() {
        return this.format;
    }

    /**
     * Set the format property: File format.
     * 
     * @param format the format value to set.
     * @return the ImportRDBParameters object itself.
     */
    public ImportRDBParameters setFormat(String format) {
        this.format = format;
        return this;
    }

    /**
     * Get the files property: files to import.
     * 
     * @return the files value.
     */
    public List<String> getFiles() {
        return this.files;
    }

    /**
     * Set the files property: files to import.
     * 
     * @param files the files value to set.
     * @return the ImportRDBParameters object itself.
     */
    public ImportRDBParameters setFiles(List<String> files) {
        this.files = files;
        return this;
    }

    /**
     * Get the preferredDataArchiveAuthMethod property: Preferred auth method to communicate to storage account used for
     * data archive, specify SAS or ManagedIdentity, default value is SAS.
     * 
     * @return the preferredDataArchiveAuthMethod value.
     */
    public String getPreferredDataArchiveAuthMethod() {
        return this.preferredDataArchiveAuthMethod;
    }

    /**
     * Set the preferredDataArchiveAuthMethod property: Preferred auth method to communicate to storage account used for
     * data archive, specify SAS or ManagedIdentity, default value is SAS.
     * 
     * @param preferredDataArchiveAuthMethod the preferredDataArchiveAuthMethod value to set.
     * @return the ImportRDBParameters object itself.
     */
    public ImportRDBParameters setPreferredDataArchiveAuthMethod(String preferredDataArchiveAuthMethod) {
        this.preferredDataArchiveAuthMethod = preferredDataArchiveAuthMethod;
        return this;
    }

    /**
     * Get the storageSubscriptionId property: Subscription id of the storage container containing files to import using
     * Managed Identity.
     * 
     * @return the storageSubscriptionId value.
     */
    public String getStorageSubscriptionId() {
        return this.storageSubscriptionId;
    }

    /**
     * Set the storageSubscriptionId property: Subscription id of the storage container containing files to import using
     * Managed Identity.
     * 
     * @param storageSubscriptionId the storageSubscriptionId value to set.
     * @return the ImportRDBParameters object itself.
     */
    public ImportRDBParameters setStorageSubscriptionId(String storageSubscriptionId) {
        this.storageSubscriptionId = storageSubscriptionId;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("files", this.files, (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("format", this.format);
        jsonWriter.writeStringField("preferred-data-archive-auth-method", this.preferredDataArchiveAuthMethod);
        jsonWriter.writeStringField("storage-subscription-id", this.storageSubscriptionId);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ImportRDBParameters from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ImportRDBParameters if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ImportRDBParameters.
     */
    public static ImportRDBParameters fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ImportRDBParameters deserializedImportRDBParameters = new ImportRDBParameters();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("files".equals(fieldName)) {
                    List<String> files = reader.readArray(reader1 -> reader1.getString());
                    deserializedImportRDBParameters.files = files;
                } else if ("format".equals(fieldName)) {
                    deserializedImportRDBParameters.format = reader.getString();
                } else if ("preferred-data-archive-auth-method".equals(fieldName)) {
                    deserializedImportRDBParameters.preferredDataArchiveAuthMethod = reader.getString();
                } else if ("storage-subscription-id".equals(fieldName)) {
                    deserializedImportRDBParameters.storageSubscriptionId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedImportRDBParameters;
        });
    }
}
