// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The response of listUpgradeNotifications.
 */
@Fluent
public final class NotificationListResponse implements JsonSerializable<NotificationListResponse> {
    /*
     * List of all notifications.
     */
    private List<UpgradeNotification> value;

    /*
     * Link for next set of notifications.
     */
    private String nextLink;

    /**
     * Creates an instance of NotificationListResponse class.
     */
    public NotificationListResponse() {
    }

    /**
     * Get the value property: List of all notifications.
     * 
     * @return the value value.
     */
    public List<UpgradeNotification> getValue() {
        return this.value;
    }

    /**
     * Set the value property: List of all notifications.
     * 
     * @param value the value value to set.
     * @return the NotificationListResponse object itself.
     */
    public NotificationListResponse setValue(List<UpgradeNotification> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Link for next set of notifications.
     * 
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("value", this.value, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of NotificationListResponse from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of NotificationListResponse if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the NotificationListResponse.
     */
    public static NotificationListResponse fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            NotificationListResponse deserializedNotificationListResponse = new NotificationListResponse();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("value".equals(fieldName)) {
                    List<UpgradeNotification> value
                        = reader.readArray(reader1 -> UpgradeNotification.fromJson(reader1));
                    deserializedNotificationListResponse.value = value;
                } else if ("nextLink".equals(fieldName)) {
                    deserializedNotificationListResponse.nextLink = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedNotificationListResponse;
        });
    }
}
