// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The response of list firewall rules Redis operation.
 */
@Fluent
public final class RedisFirewallRuleListResult implements JsonSerializable<RedisFirewallRuleListResult> {
    /*
     * Results of the list firewall rules operation.
     */
    private List<RedisFirewallRule> value;

    /*
     * Link for next page of results.
     */
    private String nextLink;

    /**
     * Creates an instance of RedisFirewallRuleListResult class.
     */
    public RedisFirewallRuleListResult() {
    }

    /**
     * Get the value property: Results of the list firewall rules operation.
     * 
     * @return the value value.
     */
    public List<RedisFirewallRule> getValue() {
        return this.value;
    }

    /**
     * Set the value property: Results of the list firewall rules operation.
     * 
     * @param value the value value to set.
     * @return the RedisFirewallRuleListResult object itself.
     */
    public RedisFirewallRuleListResult setValue(List<RedisFirewallRule> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Link for next page of results.
     * 
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("value", this.value, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RedisFirewallRuleListResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RedisFirewallRuleListResult if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the RedisFirewallRuleListResult.
     */
    public static RedisFirewallRuleListResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RedisFirewallRuleListResult deserializedRedisFirewallRuleListResult = new RedisFirewallRuleListResult();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("value".equals(fieldName)) {
                    List<RedisFirewallRule> value = reader.readArray(reader1 -> RedisFirewallRule.fromJson(reader1));
                    deserializedRedisFirewallRuleListResult.value = value;
                } else if ("nextLink".equals(fieldName)) {
                    deserializedRedisFirewallRuleListResult.nextLink = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedRedisFirewallRuleListResult;
        });
    }
}
