// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * A firewall rule on a redis cache has a name, and describes a contiguous range of IP addresses permitted to connect.
 */
@Fluent
public class RedisFirewallRule extends ProxyResource {
    /*
     * lowest IP address included in the range
     */
    private String startIP;

    /*
     * highest IP address included in the range
     */
    private String endIP;

    /*
     * The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
     */
    private String type;

    /*
     * The name of the resource
     */
    private String name;

    /*
     * Fully qualified resource ID for the resource. Ex -
     * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{
     * resourceType}/{resourceName}
     */
    private String id;

    /**
     * Creates an instance of RedisFirewallRule class.
     */
    public RedisFirewallRule() {
    }

    /**
     * Get the startIP property: lowest IP address included in the range.
     * 
     * @return the startIP value.
     */
    public String getStartIP() {
        return this.startIP;
    }

    /**
     * Set the startIP property: lowest IP address included in the range.
     * 
     * @param startIP the startIP value to set.
     * @return the RedisFirewallRule object itself.
     */
    public RedisFirewallRule setStartIP(String startIP) {
        this.startIP = startIP;
        return this;
    }

    /**
     * Get the endIP property: highest IP address included in the range.
     * 
     * @return the endIP value.
     */
    public String getEndIP() {
        return this.endIP;
    }

    /**
     * Set the endIP property: highest IP address included in the range.
     * 
     * @param endIP the endIP value to set.
     * @return the RedisFirewallRule object itself.
     */
    public RedisFirewallRule setEndIP(String endIP) {
        this.endIP = endIP;
        return this;
    }

    /**
     * Get the type property: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     * "Microsoft.Storage/storageAccounts".
     * 
     * @return the type value.
     */
    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Get the name property: The name of the resource.
     * 
     * @return the name value.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Get the id property: Fully qualified resource ID for the resource. Ex -
     * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
     * 
     * @return the id value.
     */
    @Override
    public String getId() {
        return this.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        if (startIP != null || endIP != null) {
            jsonWriter.writeStartObject("properties");
            jsonWriter.writeStringField("startIP", this.startIP);
            jsonWriter.writeStringField("endIP", this.endIP);
            jsonWriter.writeEndObject();
        }
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RedisFirewallRule from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RedisFirewallRule if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the RedisFirewallRule.
     */
    public static RedisFirewallRule fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RedisFirewallRule deserializedRedisFirewallRule = new RedisFirewallRule();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    deserializedRedisFirewallRule.id = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedRedisFirewallRule.name = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedRedisFirewallRule.type = reader.getString();
                } else if ("properties".equals(fieldName) && reader.currentToken() == JsonToken.START_OBJECT) {
                    while (reader.nextToken() != JsonToken.END_OBJECT) {
                        fieldName = reader.getFieldName();
                        reader.nextToken();

                        if ("startIP".equals(fieldName)) {
                            deserializedRedisFirewallRule.startIP = reader.getString();
                        } else if ("endIP".equals(fieldName)) {
                            deserializedRedisFirewallRule.endIP = reader.getString();
                        } else {
                            reader.skipChildren();
                        }
                    }
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedRedisFirewallRule;
        });
    }
}
