// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The response of list Redis operation.
 */
@Fluent
public final class RedisListResult implements JsonSerializable<RedisListResult> {
    /*
     * List of Redis cache instances.
     */
    private List<RedisResource> value;

    /*
     * Link for next page of results.
     */
    private String nextLink;

    /**
     * Creates an instance of RedisListResult class.
     */
    public RedisListResult() {
    }

    /**
     * Get the value property: List of Redis cache instances.
     * 
     * @return the value value.
     */
    public List<RedisResource> getValue() {
        return this.value;
    }

    /**
     * Set the value property: List of Redis cache instances.
     * 
     * @param value the value value to set.
     * @return the RedisListResult object itself.
     */
    public RedisListResult setValue(List<RedisResource> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Link for next page of results.
     * 
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("value", this.value, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RedisListResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RedisListResult if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IOException If an error occurs while reading the RedisListResult.
     */
    public static RedisListResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RedisListResult deserializedRedisListResult = new RedisListResult();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("value".equals(fieldName)) {
                    List<RedisResource> value = reader.readArray(reader1 -> RedisResource.fromJson(reader1));
                    deserializedRedisListResult.value = value;
                } else if ("nextLink".equals(fieldName)) {
                    deserializedRedisListResult.nextLink = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedRedisListResult;
        });
    }
}
