// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * A single Redis item in List or Get Operation.
 */
@Fluent
public class RedisResource extends TrackedResource {
    /*
     * A list of availability zones denoting where the resource needs to come from.
     */
    private List<String> zones;

    /*
     * The identity of the resource.
     */
    private ManagedServiceIdentity identity;

    /*
     * All Redis Settings. Few possible keys:
     * rdb-backup-enabled,rdb-storage-connection-string,rdb-backup-frequency,maxmemory-delta,
     * maxmemory-policy,notify-keyspace-events, aof-backup-enabled, aof-storage-connection-string-0,
     * aof-storage-connection-string-1 etc.
     */
    private RedisCommonPropertiesRedisConfiguration redisConfiguration;

    /*
     * Redis version. This should be in the form 'major[.minor]' (only 'major' is required) or the value 'latest' which
     * refers to the latest stable Redis version that is available. Supported versions: 4.0, 6.0 (latest). Default value
     * is 'latest'.
     */
    private String redisVersion;

    /*
     * Specifies whether the non-ssl Redis server port (6379) is enabled.
     */
    private Boolean enableNonSslPort;

    /*
     * The number of replicas to be created per primary.
     */
    private Integer replicasPerMaster;

    /*
     * The number of replicas to be created per primary.
     */
    private Integer replicasPerPrimary;

    /*
     * A dictionary of tenant settings
     */
    private Map<String, String> tenantSettings;

    /*
     * The number of shards to be created on a Premium Cluster Cache.
     */
    private Integer shardCount;

    /*
     * Optional: requires clients to use a specified TLS version (or higher) to connect (e,g, '1.0', '1.1', '1.2')
     */
    private TlsVersion minimumTlsVersion;

    /*
     * Whether or not public endpoint access is allowed for this cache. Value is optional but if passed in, must be
     * 'Enabled' or 'Disabled'. If 'Disabled', private endpoints are the exclusive access method. Default value is
     * 'Enabled'
     */
    private PublicNetworkAccess publicNetworkAccess;

    /*
     * Optional: Specifies the update channel for the monthly Redis updates your Redis Cache will receive. Caches using
     * 'Preview' update channel get latest Redis updates at least 4 weeks ahead of 'Stable' channel caches. Default
     * value is 'Stable'.
     */
    private UpdateChannel updateChannel;

    /*
     * Authentication to Redis through access keys is disabled when set as true. Default value is false.
     */
    private Boolean disableAccessKeyAuthentication;

    /*
     * Optional: Specifies how availability zones are allocated to the Redis cache. 'Automatic' enables zone redundancy
     * and Azure will select zones based on regional availability and capacity. 'UserDefined' will select availability
     * zones passed in by you using the 'zones' parameter. 'NoZones' will produce a non-zonal cache. If
     * 'zonalAllocation' is not passed, it will be set to 'UserDefined' when zones are passed in, otherwise, will be set
     * to 'NoZones'
     */
    private ZonalAllocationPolicy zonalAllocationPolicy;

    /*
     * The SKU of the Redis cache to deploy.
     */
    private Sku sku;

    /*
     * The full resource ID of a subnet in a virtual network to deploy the Redis cache in. Example format:
     * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/Microsoft.{Network|ClassicNetwork}/
     * VirtualNetworks/vnet1/subnets/subnet1
     */
    private String subnetId;

    /*
     * Static IP address. Optionally, may be specified when deploying a Redis cache inside an existing Azure Virtual
     * Network; auto assigned by default.
     */
    private String staticIP;

    /*
     * Redis instance provisioning status.
     */
    private ProvisioningState provisioningState;

    /*
     * Redis host name.
     */
    private String hostName;

    /*
     * Redis non-SSL port.
     */
    private Integer port;

    /*
     * Redis SSL port.
     */
    private Integer sslPort;

    /*
     * The keys of the Redis cache - not set if this object is not the response to Create or Update redis cache
     */
    private RedisAccessKeys accessKeys;

    /*
     * List of the linked servers associated with the cache
     */
    private List<RedisLinkedServer> linkedServers;

    /*
     * List of the Redis instances associated with the cache
     */
    private List<RedisInstanceDetails> instances;

    /*
     * List of private endpoint connection associated with the specified redis cache
     */
    private List<PrivateEndpointConnection> privateEndpointConnections;

    /*
     * The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
     */
    private String type;

    /*
     * The name of the resource
     */
    private String name;

    /*
     * Fully qualified resource ID for the resource. Ex -
     * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{
     * resourceType}/{resourceName}
     */
    private String id;

    /**
     * Creates an instance of RedisResource class.
     */
    public RedisResource() {
    }

    /**
     * Get the zones property: A list of availability zones denoting where the resource needs to come from.
     * 
     * @return the zones value.
     */
    public List<String> getZones() {
        return this.zones;
    }

    /**
     * Set the zones property: A list of availability zones denoting where the resource needs to come from.
     * 
     * @param zones the zones value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setZones(List<String> zones) {
        this.zones = zones;
        return this;
    }

    /**
     * Get the identity property: The identity of the resource.
     * 
     * @return the identity value.
     */
    public ManagedServiceIdentity getIdentity() {
        return this.identity;
    }

    /**
     * Set the identity property: The identity of the resource.
     * 
     * @param identity the identity value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setIdentity(ManagedServiceIdentity identity) {
        this.identity = identity;
        return this;
    }

    /**
     * Get the redisConfiguration property: All Redis Settings. Few possible keys:
     * rdb-backup-enabled,rdb-storage-connection-string,rdb-backup-frequency,maxmemory-delta,
     * maxmemory-policy,notify-keyspace-events, aof-backup-enabled, aof-storage-connection-string-0,
     * aof-storage-connection-string-1 etc.
     * 
     * @return the redisConfiguration value.
     */
    public RedisCommonPropertiesRedisConfiguration getRedisConfiguration() {
        return this.redisConfiguration;
    }

    /**
     * Set the redisConfiguration property: All Redis Settings. Few possible keys:
     * rdb-backup-enabled,rdb-storage-connection-string,rdb-backup-frequency,maxmemory-delta,
     * maxmemory-policy,notify-keyspace-events, aof-backup-enabled, aof-storage-connection-string-0,
     * aof-storage-connection-string-1 etc.
     * 
     * @param redisConfiguration the redisConfiguration value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setRedisConfiguration(RedisCommonPropertiesRedisConfiguration redisConfiguration) {
        this.redisConfiguration = redisConfiguration;
        return this;
    }

    /**
     * Get the redisVersion property: Redis version. This should be in the form 'major[.minor]' (only 'major' is
     * required) or the value 'latest' which refers to the latest stable Redis version that is available. Supported
     * versions: 4.0, 6.0 (latest). Default value is 'latest'.
     * 
     * @return the redisVersion value.
     */
    public String getRedisVersion() {
        return this.redisVersion;
    }

    /**
     * Set the redisVersion property: Redis version. This should be in the form 'major[.minor]' (only 'major' is
     * required) or the value 'latest' which refers to the latest stable Redis version that is available. Supported
     * versions: 4.0, 6.0 (latest). Default value is 'latest'.
     * 
     * @param redisVersion the redisVersion value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setRedisVersion(String redisVersion) {
        this.redisVersion = redisVersion;
        return this;
    }

    /**
     * Get the enableNonSslPort property: Specifies whether the non-ssl Redis server port (6379) is enabled.
     * 
     * @return the enableNonSslPort value.
     */
    public Boolean isEnableNonSslPort() {
        return this.enableNonSslPort;
    }

    /**
     * Set the enableNonSslPort property: Specifies whether the non-ssl Redis server port (6379) is enabled.
     * 
     * @param enableNonSslPort the enableNonSslPort value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setEnableNonSslPort(Boolean enableNonSslPort) {
        this.enableNonSslPort = enableNonSslPort;
        return this;
    }

    /**
     * Get the replicasPerMaster property: The number of replicas to be created per primary.
     * 
     * @return the replicasPerMaster value.
     */
    public Integer getReplicasPerMaster() {
        return this.replicasPerMaster;
    }

    /**
     * Set the replicasPerMaster property: The number of replicas to be created per primary.
     * 
     * @param replicasPerMaster the replicasPerMaster value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setReplicasPerMaster(Integer replicasPerMaster) {
        this.replicasPerMaster = replicasPerMaster;
        return this;
    }

    /**
     * Get the replicasPerPrimary property: The number of replicas to be created per primary.
     * 
     * @return the replicasPerPrimary value.
     */
    public Integer getReplicasPerPrimary() {
        return this.replicasPerPrimary;
    }

    /**
     * Set the replicasPerPrimary property: The number of replicas to be created per primary.
     * 
     * @param replicasPerPrimary the replicasPerPrimary value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setReplicasPerPrimary(Integer replicasPerPrimary) {
        this.replicasPerPrimary = replicasPerPrimary;
        return this;
    }

    /**
     * Get the tenantSettings property: A dictionary of tenant settings.
     * 
     * @return the tenantSettings value.
     */
    public Map<String, String> getTenantSettings() {
        return this.tenantSettings;
    }

    /**
     * Set the tenantSettings property: A dictionary of tenant settings.
     * 
     * @param tenantSettings the tenantSettings value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setTenantSettings(Map<String, String> tenantSettings) {
        this.tenantSettings = tenantSettings;
        return this;
    }

    /**
     * Get the shardCount property: The number of shards to be created on a Premium Cluster Cache.
     * 
     * @return the shardCount value.
     */
    public Integer getShardCount() {
        return this.shardCount;
    }

    /**
     * Set the shardCount property: The number of shards to be created on a Premium Cluster Cache.
     * 
     * @param shardCount the shardCount value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setShardCount(Integer shardCount) {
        this.shardCount = shardCount;
        return this;
    }

    /**
     * Get the minimumTlsVersion property: Optional: requires clients to use a specified TLS version (or higher) to
     * connect (e,g, '1.0', '1.1', '1.2').
     * 
     * @return the minimumTlsVersion value.
     */
    public TlsVersion getMinimumTlsVersion() {
        return this.minimumTlsVersion;
    }

    /**
     * Set the minimumTlsVersion property: Optional: requires clients to use a specified TLS version (or higher) to
     * connect (e,g, '1.0', '1.1', '1.2').
     * 
     * @param minimumTlsVersion the minimumTlsVersion value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setMinimumTlsVersion(TlsVersion minimumTlsVersion) {
        this.minimumTlsVersion = minimumTlsVersion;
        return this;
    }

    /**
     * Get the publicNetworkAccess property: Whether or not public endpoint access is allowed for this cache. Value is
     * optional but if passed in, must be 'Enabled' or 'Disabled'. If 'Disabled', private endpoints are the exclusive
     * access method. Default value is 'Enabled'.
     * 
     * @return the publicNetworkAccess value.
     */
    public PublicNetworkAccess getPublicNetworkAccess() {
        return this.publicNetworkAccess;
    }

    /**
     * Set the publicNetworkAccess property: Whether or not public endpoint access is allowed for this cache. Value is
     * optional but if passed in, must be 'Enabled' or 'Disabled'. If 'Disabled', private endpoints are the exclusive
     * access method. Default value is 'Enabled'.
     * 
     * @param publicNetworkAccess the publicNetworkAccess value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setPublicNetworkAccess(PublicNetworkAccess publicNetworkAccess) {
        this.publicNetworkAccess = publicNetworkAccess;
        return this;
    }

    /**
     * Get the updateChannel property: Optional: Specifies the update channel for the monthly Redis updates your Redis
     * Cache will receive. Caches using 'Preview' update channel get latest Redis updates at least 4 weeks ahead of
     * 'Stable' channel caches. Default value is 'Stable'.
     * 
     * @return the updateChannel value.
     */
    public UpdateChannel getUpdateChannel() {
        return this.updateChannel;
    }

    /**
     * Set the updateChannel property: Optional: Specifies the update channel for the monthly Redis updates your Redis
     * Cache will receive. Caches using 'Preview' update channel get latest Redis updates at least 4 weeks ahead of
     * 'Stable' channel caches. Default value is 'Stable'.
     * 
     * @param updateChannel the updateChannel value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setUpdateChannel(UpdateChannel updateChannel) {
        this.updateChannel = updateChannel;
        return this;
    }

    /**
     * Get the disableAccessKeyAuthentication property: Authentication to Redis through access keys is disabled when set
     * as true. Default value is false.
     * 
     * @return the disableAccessKeyAuthentication value.
     */
    public Boolean isDisableAccessKeyAuthentication() {
        return this.disableAccessKeyAuthentication;
    }

    /**
     * Set the disableAccessKeyAuthentication property: Authentication to Redis through access keys is disabled when set
     * as true. Default value is false.
     * 
     * @param disableAccessKeyAuthentication the disableAccessKeyAuthentication value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setDisableAccessKeyAuthentication(Boolean disableAccessKeyAuthentication) {
        this.disableAccessKeyAuthentication = disableAccessKeyAuthentication;
        return this;
    }

    /**
     * Get the zonalAllocationPolicy property: Optional: Specifies how availability zones are allocated to the Redis
     * cache. 'Automatic' enables zone redundancy and Azure will select zones based on regional availability and
     * capacity. 'UserDefined' will select availability zones passed in by you using the 'zones' parameter. 'NoZones'
     * will produce a non-zonal cache. If 'zonalAllocation' is not passed, it will be set to 'UserDefined' when zones
     * are passed in, otherwise, will be set to 'NoZones'.
     * 
     * @return the zonalAllocationPolicy value.
     */
    public ZonalAllocationPolicy getZonalAllocationPolicy() {
        return this.zonalAllocationPolicy;
    }

    /**
     * Set the zonalAllocationPolicy property: Optional: Specifies how availability zones are allocated to the Redis
     * cache. 'Automatic' enables zone redundancy and Azure will select zones based on regional availability and
     * capacity. 'UserDefined' will select availability zones passed in by you using the 'zones' parameter. 'NoZones'
     * will produce a non-zonal cache. If 'zonalAllocation' is not passed, it will be set to 'UserDefined' when zones
     * are passed in, otherwise, will be set to 'NoZones'.
     * 
     * @param zonalAllocationPolicy the zonalAllocationPolicy value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setZonalAllocationPolicy(ZonalAllocationPolicy zonalAllocationPolicy) {
        this.zonalAllocationPolicy = zonalAllocationPolicy;
        return this;
    }

    /**
     * Get the sku property: The SKU of the Redis cache to deploy.
     * 
     * @return the sku value.
     */
    public Sku getSku() {
        return this.sku;
    }

    /**
     * Set the sku property: The SKU of the Redis cache to deploy.
     * 
     * @param sku the sku value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setSku(Sku sku) {
        this.sku = sku;
        return this;
    }

    /**
     * Get the subnetId property: The full resource ID of a subnet in a virtual network to deploy the Redis cache in.
     * Example format:
     * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/Microsoft.{Network|ClassicNetwork}/VirtualNetworks/vnet1/subnets/subnet1.
     * 
     * @return the subnetId value.
     */
    public String getSubnetId() {
        return this.subnetId;
    }

    /**
     * Set the subnetId property: The full resource ID of a subnet in a virtual network to deploy the Redis cache in.
     * Example format:
     * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/Microsoft.{Network|ClassicNetwork}/VirtualNetworks/vnet1/subnets/subnet1.
     * 
     * @param subnetId the subnetId value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setSubnetId(String subnetId) {
        this.subnetId = subnetId;
        return this;
    }

    /**
     * Get the staticIP property: Static IP address. Optionally, may be specified when deploying a Redis cache inside an
     * existing Azure Virtual Network; auto assigned by default.
     * 
     * @return the staticIP value.
     */
    public String getStaticIP() {
        return this.staticIP;
    }

    /**
     * Set the staticIP property: Static IP address. Optionally, may be specified when deploying a Redis cache inside an
     * existing Azure Virtual Network; auto assigned by default.
     * 
     * @param staticIP the staticIP value to set.
     * @return the RedisResource object itself.
     */
    public RedisResource setStaticIP(String staticIP) {
        this.staticIP = staticIP;
        return this;
    }

    /**
     * Get the provisioningState property: Redis instance provisioning status.
     * 
     * @return the provisioningState value.
     */
    public ProvisioningState getProvisioningState() {
        return this.provisioningState;
    }

    /**
     * Get the hostName property: Redis host name.
     * 
     * @return the hostName value.
     */
    public String getHostName() {
        return this.hostName;
    }

    /**
     * Get the port property: Redis non-SSL port.
     * 
     * @return the port value.
     */
    public Integer getPort() {
        return this.port;
    }

    /**
     * Get the sslPort property: Redis SSL port.
     * 
     * @return the sslPort value.
     */
    public Integer getSslPort() {
        return this.sslPort;
    }

    /**
     * Get the accessKeys property: The keys of the Redis cache - not set if this object is not the response to Create
     * or Update redis cache.
     * 
     * @return the accessKeys value.
     */
    public RedisAccessKeys getAccessKeys() {
        return this.accessKeys;
    }

    /**
     * Get the linkedServers property: List of the linked servers associated with the cache.
     * 
     * @return the linkedServers value.
     */
    public List<RedisLinkedServer> getLinkedServers() {
        return this.linkedServers;
    }

    /**
     * Get the instances property: List of the Redis instances associated with the cache.
     * 
     * @return the instances value.
     */
    public List<RedisInstanceDetails> getInstances() {
        return this.instances;
    }

    /**
     * Get the privateEndpointConnections property: List of private endpoint connection associated with the specified
     * redis cache.
     * 
     * @return the privateEndpointConnections value.
     */
    public List<PrivateEndpointConnection> getPrivateEndpointConnections() {
        return this.privateEndpointConnections;
    }

    /**
     * Get the type property: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     * "Microsoft.Storage/storageAccounts".
     * 
     * @return the type value.
     */
    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Get the name property: The name of the resource.
     * 
     * @return the name value.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Get the id property: Fully qualified resource ID for the resource. Ex -
     * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
     * 
     * @return the id value.
     */
    @Override
    public String getId() {
        return this.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedisResource setTags(Map<String, String> tags) {
        super.setTags(tags);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedisResource setLocation(String location) {
        super.setLocation(location);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("location", getLocation());
        jsonWriter.writeMapField("tags", getTags(), (writer, element) -> writer.writeString(element));
        jsonWriter.writeArrayField("zones", this.zones, (writer, element) -> writer.writeString(element));
        jsonWriter.writeJsonField("identity", this.identity);
        if (redisConfiguration != null
            || redisVersion != null
            || enableNonSslPort != null
            || replicasPerMaster != null
            || replicasPerPrimary != null
            || tenantSettings != null
            || shardCount != null
            || minimumTlsVersion != null
            || publicNetworkAccess != null
            || updateChannel != null
            || disableAccessKeyAuthentication != null
            || zonalAllocationPolicy != null
            || sku != null
            || subnetId != null
            || staticIP != null
            || provisioningState != null
            || hostName != null
            || port != null
            || sslPort != null
            || accessKeys != null
            || linkedServers != null
            || instances != null
            || privateEndpointConnections != null) {
            jsonWriter.writeStartObject("properties");
            jsonWriter.writeJsonField("redisConfiguration", this.redisConfiguration);
            jsonWriter.writeStringField("redisVersion", this.redisVersion);
            jsonWriter.writeBooleanField("enableNonSslPort", this.enableNonSslPort);
            jsonWriter.writeNumberField("replicasPerMaster", this.replicasPerMaster);
            jsonWriter.writeNumberField("replicasPerPrimary", this.replicasPerPrimary);
            jsonWriter.writeMapField("tenantSettings", this.tenantSettings,
                (writer, element) -> writer.writeString(element));
            jsonWriter.writeNumberField("shardCount", this.shardCount);
            jsonWriter.writeStringField("minimumTlsVersion",
                this.minimumTlsVersion == null ? null : this.minimumTlsVersion.toString());
            jsonWriter.writeStringField("publicNetworkAccess",
                this.publicNetworkAccess == null ? null : this.publicNetworkAccess.toString());
            jsonWriter.writeStringField("updateChannel",
                this.updateChannel == null ? null : this.updateChannel.toString());
            jsonWriter.writeBooleanField("disableAccessKeyAuthentication", this.disableAccessKeyAuthentication);
            jsonWriter.writeStringField("zonalAllocationPolicy",
                this.zonalAllocationPolicy == null ? null : this.zonalAllocationPolicy.toString());
            jsonWriter.writeJsonField("sku", this.sku);
            jsonWriter.writeStringField("subnetId", this.subnetId);
            jsonWriter.writeStringField("staticIP", this.staticIP);
            jsonWriter.writeEndObject();
        }
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RedisResource from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RedisResource if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the RedisResource.
     */
    public static RedisResource fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RedisResource deserializedRedisResource = new RedisResource();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("location".equals(fieldName)) {
                    deserializedRedisResource.setLocation(reader.getString());
                } else if ("id".equals(fieldName)) {
                    deserializedRedisResource.id = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedRedisResource.name = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedRedisResource.type = reader.getString();
                } else if ("tags".equals(fieldName)) {
                    Map<String, String> tags = reader.readMap(reader1 -> reader1.getString());
                    deserializedRedisResource.setTags(tags);
                } else if ("zones".equals(fieldName)) {
                    List<String> zones = reader.readArray(reader1 -> reader1.getString());
                    deserializedRedisResource.zones = zones;
                } else if ("identity".equals(fieldName)) {
                    deserializedRedisResource.identity = ManagedServiceIdentity.fromJson(reader);
                } else if ("properties".equals(fieldName) && reader.currentToken() == JsonToken.START_OBJECT) {
                    while (reader.nextToken() != JsonToken.END_OBJECT) {
                        fieldName = reader.getFieldName();
                        reader.nextToken();

                        if ("redisConfiguration".equals(fieldName)) {
                            deserializedRedisResource.redisConfiguration
                                = RedisCommonPropertiesRedisConfiguration.fromJson(reader);
                        } else if ("redisVersion".equals(fieldName)) {
                            deserializedRedisResource.redisVersion = reader.getString();
                        } else if ("enableNonSslPort".equals(fieldName)) {
                            deserializedRedisResource.enableNonSslPort = reader.getNullable(JsonReader::getBoolean);
                        } else if ("replicasPerMaster".equals(fieldName)) {
                            deserializedRedisResource.replicasPerMaster = reader.getNullable(JsonReader::getInt);
                        } else if ("replicasPerPrimary".equals(fieldName)) {
                            deserializedRedisResource.replicasPerPrimary = reader.getNullable(JsonReader::getInt);
                        } else if ("tenantSettings".equals(fieldName)) {
                            Map<String, String> tenantSettings = reader.readMap(reader1 -> reader1.getString());
                            deserializedRedisResource.tenantSettings = tenantSettings;
                        } else if ("shardCount".equals(fieldName)) {
                            deserializedRedisResource.shardCount = reader.getNullable(JsonReader::getInt);
                        } else if ("minimumTlsVersion".equals(fieldName)) {
                            deserializedRedisResource.minimumTlsVersion = TlsVersion.fromString(reader.getString());
                        } else if ("publicNetworkAccess".equals(fieldName)) {
                            deserializedRedisResource.publicNetworkAccess
                                = PublicNetworkAccess.fromString(reader.getString());
                        } else if ("updateChannel".equals(fieldName)) {
                            deserializedRedisResource.updateChannel = UpdateChannel.fromString(reader.getString());
                        } else if ("disableAccessKeyAuthentication".equals(fieldName)) {
                            deserializedRedisResource.disableAccessKeyAuthentication
                                = reader.getNullable(JsonReader::getBoolean);
                        } else if ("zonalAllocationPolicy".equals(fieldName)) {
                            deserializedRedisResource.zonalAllocationPolicy
                                = ZonalAllocationPolicy.fromString(reader.getString());
                        } else if ("sku".equals(fieldName)) {
                            deserializedRedisResource.sku = Sku.fromJson(reader);
                        } else if ("subnetId".equals(fieldName)) {
                            deserializedRedisResource.subnetId = reader.getString();
                        } else if ("staticIP".equals(fieldName)) {
                            deserializedRedisResource.staticIP = reader.getString();
                        } else if ("provisioningState".equals(fieldName)) {
                            deserializedRedisResource.provisioningState
                                = ProvisioningState.fromString(reader.getString());
                        } else if ("hostName".equals(fieldName)) {
                            deserializedRedisResource.hostName = reader.getString();
                        } else if ("port".equals(fieldName)) {
                            deserializedRedisResource.port = reader.getNullable(JsonReader::getInt);
                        } else if ("sslPort".equals(fieldName)) {
                            deserializedRedisResource.sslPort = reader.getNullable(JsonReader::getInt);
                        } else if ("accessKeys".equals(fieldName)) {
                            deserializedRedisResource.accessKeys = RedisAccessKeys.fromJson(reader);
                        } else if ("linkedServers".equals(fieldName)) {
                            List<RedisLinkedServer> linkedServers
                                = reader.readArray(reader1 -> RedisLinkedServer.fromJson(reader1));
                            deserializedRedisResource.linkedServers = linkedServers;
                        } else if ("instances".equals(fieldName)) {
                            List<RedisInstanceDetails> instances
                                = reader.readArray(reader1 -> RedisInstanceDetails.fromJson(reader1));
                            deserializedRedisResource.instances = instances;
                        } else if ("privateEndpointConnections".equals(fieldName)) {
                            List<PrivateEndpointConnection> privateEndpointConnections
                                = reader.readArray(reader1 -> PrivateEndpointConnection.fromJson(reader1));
                            deserializedRedisResource.privateEndpointConnections = privateEndpointConnections;
                        } else {
                            reader.skipChildren();
                        }
                    }
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedRedisResource;
        });
    }
}
