// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rediscache.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Optional: requires clients to use a specified TLS version (or higher) to connect (e,g, '1.0', '1.1', '1.2').
 */
public final class TlsVersion extends ExpandableStringEnum<TlsVersion> {
    /**
     * Static value 1.0 for TlsVersion.
     */
    public static final TlsVersion ONE0 = fromString("1.0");

    /**
     * Static value 1.1 for TlsVersion.
     */
    public static final TlsVersion ONE1 = fromString("1.1");

    /**
     * Static value 1.2 for TlsVersion.
     */
    public static final TlsVersion ONE2 = fromString("1.2");

    /**
     * Creates a new instance of TlsVersion value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public TlsVersion() {
    }

    /**
     * Creates or finds a TlsVersion from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding TlsVersion.
     */
    public static TlsVersion fromString(String name) {
        return fromString(name, TlsVersion.class);
    }

    /**
     * Gets known TlsVersion values.
     * 
     * @return known TlsVersion values.
     */
    public static Collection<TlsVersion> values() {
        return values(TlsVersion.class);
    }
}
